/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: false,

  // Proxy the app-owned preview tool to app.glowsocial.com while keeping the
  // public SEO URL on glowsocial.com.
  // beforeFiles: fires before routing, so slug form submissions proxy even though
  //              a static page also exists at /preview/:slug.
  // afterFiles:  proxies the generation + image APIs.
  async rewrites() {
    return {
      beforeFiles: [
        // Keep the app-owned preview tool on the main domain for SEO/AEO value.
        {
          source: '/preview',
          destination: 'https://app.glowsocial.com/preview',
        },
        // /preview/:slug?url= — vertical landing pages proxy to the app after submit.
        {
          source: '/preview/:slug',
          has: [{ type: 'query', key: 'url' }],
          destination: 'https://app.glowsocial.com/preview/:slug',
        },
      ],
      afterFiles: [
        // API routes called by PreviewClient on the marketing site.
        {
          source: '/api/preview/:path*',
          destination: 'https://app.glowsocial.com/api/preview/:path*',
        },

        // ── .well-known agent discovery endpoints ──
        // Next.js ignores dot-prefixed folders, so we rewrite to /api/well-known/*
        { source: '/.well-known/api-catalog', destination: '/api/well-known/api-catalog' },
        { source: '/.well-known/openid-configuration', destination: '/api/well-known/openid-configuration' },
        { source: '/.well-known/oauth-protected-resource', destination: '/api/well-known/oauth-protected-resource' },
        { source: '/.well-known/mcp/server-card.json', destination: '/api/well-known/mcp-server-card' },
        { source: '/.well-known/agent-skills/index.json', destination: '/api/well-known/agent-skills-index' },
        { source: '/.well-known/agent-skills/SKILL.md', destination: '/api/well-known/agent-skills-md' },
        { source: '/.well-known/ucp', destination: '/api/well-known/ucp' },
        { source: '/.well-known/acp.json', destination: '/api/well-known/acp' },
        { source: '/.well-known/agent-card.json', destination: '/api/well-known/agent-card' },
      ],
      fallback: [],
    }
  },

  async redirects() {
    return [
      // === "Time spent on social media" cluster consolidation ===
      // Merging 5 thin duplicate pages into /blog/average-time-social-media-marketing
      {
        source: "/blog/hours-per-week-social-media-takes",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },
      {
        source: "/blog/average-time-spent-social-media-marketing",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },
      {
        source: "/blog/time-small-business-social-media",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },
      {
        source: "/blog/hours-per-week-social-media",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },
      {
        source: "/blog/how-long-manage-social-media",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },
      // Root-level versions of the same (avoid double redirects)
      {
        source: "/average-time-social-media-marketing",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },
      {
        source: "/hours-per-week-social-media-takes",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },
      {
        source: "/average-time-spent-social-media-marketing",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },
      {
        source: "/time-small-business-social-media",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },
      {
        source: "/hours-per-week-social-media",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },
      {
        source: "/how-long-manage-social-media",
        destination: "/blog/average-time-social-media-marketing",
        permanent: true,
      },

      // === "Social media manager cost" consolidation ===
      // Thin (41 lines) page competing with the established cost guide (16,263 imp)
      {
        source: "/blog/how-much-does-a-social-media-manager-cost-2026",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/blog/how-much-does-a-social-media-manager-cost",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/how-much-does-a-social-media-manager-cost",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/how-much-does-a-social-media-manager-cost-2026",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },

      // === GSC duplicate URL fixes — root-level → /blog/ canonical ===
      // Root /social-media-caption-length had 1,443 impressions splitting with /blog/ version (5,010 imp)
      {
        source: "/social-media-caption-length",
        destination: "/blog/social-media-caption-length",
        permanent: true,
      },
      // Root /later-vs-buffer had impressions splitting with /blog/ version — /blog/ is canonical
      {
        source: "/later-vs-buffer-differences-comparison",
        destination: "/blog/later-vs-buffer-differences-comparison",
        permanent: true,
      },
      // Root /freelance-social-media-manager-charge-cost — 671 impressions splitting with /blog/ (15,592 imp)
      {
        source: "/freelance-social-media-manager-charge-cost",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      // Root /ai-tools-vs-agencies-cost — 4,573 impressions splitting with /blog/ (581 imp)
      {
        source: "/ai-tools-vs-agencies-cost",
        destination: "/blog/ai-tools-vs-agencies-cost",
        permanent: true,
      },
      // Root /social-media-tools-under-50 — 3,284 impressions splitting with /blog/ (135 imp)
      {
        source: "/social-media-tools-under-50",
        destination: "/blog/social-media-tools-under-50",
        permanent: true,
      },
      // Root /best-affordable-social-media-management-small-business should consolidate to the transactional hub.
      {
        source: "/best-affordable-social-media-management-small-business",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      // Root /social-media-restaurants — 1,169 imp splitting with /blog/
      {
        source: "/social-media-restaurants",
        destination: "/blog/social-media-restaurants",
        permanent: true,
      },
      // Root /social-media-home-services — 759 imp splitting with /blog/
      {
        source: "/social-media-home-services",
        destination: "/blog/social-media-home-services",
        permanent: true,
      },
      // Root /best-ai-social-media-content-generators — 701 imp splitting with /blog/ (652 imp)
      {
        source: "/best-ai-social-media-content-generators",
        destination: "/blog/best-ai-social-media-content-generators",
        permanent: true,
      },
      // Legacy automation tips URL should consolidate to the stronger automation setup guide.
      {
        source: "/10-essential-tips-for-managing-automated-social-media-accounts-effectively",
        destination: "/blog/how-to-automate-social-media-posting-for-small-business",
        permanent: true,
      },
      {
        source: "/blog/10-essential-tips-for-managing-automated-social-media-accounts-effectively",
        destination: "/blog/how-to-automate-social-media-posting-for-small-business",
        permanent: true,
      },
      {
        source: "/10-essential-tools-to-automate-twitter-for-enhanced-engagement",
        destination: "/blog/how-to-automate-social-media-posting-for-small-business",
        permanent: true,
      },
      {
        source: "/blog/10-essential-tools-to-automate-twitter-for-enhanced-engagement",
        destination: "/blog/how-to-automate-social-media-posting-for-small-business",
        permanent: true,
      },
      {
        source: "/49-social-media-management-roofers",
        destination: "/blog/automated-social-media-roofers-contractors",
        permanent: true,
      },
      ...[
        {
          slug: "a-comprehensive-guide-on-how-to-advertise-on-fb-marketplace-effectively",
          canonical: "/blog/facebook-for-small-business-minimum-posting-strategy",
        },
        {
          slug: "a-comprehensive-guide-to-competitive-analysis-on-social-media",
          canonical: "/blog/automate-social-media-oba-framework",
        },
        {
          slug: "a-comprehensive-guide-to-using-autopost-software-for-social-media",
          canonical: "/blog/social-media-on-autopilot",
        },
        {
          slug: "ab-test-headlines-ctas-oba-campaigns",
          canonical: "/blog/automate-social-media-oba-framework",
        },
      ].flatMap(({ slug, canonical }) => [
        {
          source: `/${slug}`,
          destination: canonical,
          permanent: true,
        },
        {
          source: `/blog/${slug}`,
          destination: canonical,
          permanent: true,
        },
      ]),
      ...[
        {
          slug: "accountants-financial-advisors-visibility-no-ads",
          canonical: "/blog/best-social-media-service-for-accountants",
          includeBlogVariant: true,
        },
        {
          slug: "adapt-business-post-multiple-platforms",
          canonical: "/blog/how-to-automatically-post-to-all-social-media-platforms",
          includeBlogVariant: true,
        },
        {
          slug: "adapt-social-media-strategy-ai-future-trends",
          canonical: "/blog/how-ai-social-media-posting-works",
          includeBlogVariant: true,
        },
        {
          slug: "affordable-social-media-for-attorneys",
          canonical: "/blog/done-for-you-ai-social-media-law-firms",
          includeBlogVariant: true,
        },
        {
          slug: "ai-captions-a-step-by-step-tutorial",
          canonical: "/blog/can-ai-write-good-social-media-posts",
          includeBlogVariant: true,
        },
        {
          slug: "ai-replace-social-media-manager",
          canonical: "/blog/social-media-manager-vs-ai",
          includeBlogVariant: false,
        },
        {
          slug: "ai-replacing-google-local-business-discovery",
          canonical: "/blog/how-ai-social-media-posting-works",
          includeBlogVariant: false,
        },
        {
          slug: "ai-small-business-marketing-oba-framework",
          canonical: "/blog/oba-social-media-framework-local-business",
          includeBlogVariant: true,
        },
      ].flatMap(({ slug, canonical, includeBlogVariant }) => [
        {
          source: `/${slug}`,
          destination: canonical,
          permanent: true,
        },
        ...(includeBlogVariant
          ? [
              {
                source: `/blog/${slug}`,
                destination: canonical,
                permanent: true,
              },
            ]
          : []),
      ]),

      // === "SM manager cost" cluster consolidation ===
      // Merging thin duplicate cost pages into /blog/freelance-social-media-manager-charge-cost
      {
        source: "/blog/why-social-media-managers-expensive",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/why-social-media-managers-expensive",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/blog/should-i-hire-social-media-manager-or-diy",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/should-i-hire-social-media-manager-or-diy",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/blog/hire-social-media-manager-or-do-it-yourself",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/hire-social-media-manager-or-do-it-yourself",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/blog/social-media-manager-cost-hiring-budget",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/blog/the-real-cost-of-social-media-management-comparing-your-options-in-2025",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/social-media-manager-cost-hiring-budget",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },
      {
        source: "/the-real-cost-of-social-media-management-comparing-your-options-in-2025",
        destination: "/blog/freelance-social-media-manager-charge-cost",
        permanent: true,
      },

      // === "Affordable social media management" consolidation ===
      {
        source: "/blog/affordable-social-media-management",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      {
        source: "/blog/affordable-social-media-management-guide",
        destination: "/blog/best-affordable-social-media-management-small-business",
        permanent: true,
      },
      {
        source: "/affordable-social-media-management-guide",
        destination: "/blog/best-affordable-social-media-management-small-business",
        permanent: true,
      },
      {
        source: "/blog/affordable-social-media-no-marketing-agency",
        destination: "/blog/best-affordable-social-media-management-small-business",
        permanent: true,
      },
      {
        source: "/affordable-social-media-no-marketing-agency",
        destination: "/blog/best-affordable-social-media-management-small-business",
        permanent: true,
      },
      {
        source: "/blog/affordable-social-media-vs-hootsuite",
        destination: "/blog/best-affordable-social-media-management-small-business",
        permanent: true,
      },
      {
        source: "/affordable-social-media-vs-hootsuite",
        destination: "/blog/best-affordable-social-media-management-small-business",
        permanent: true,
      },
      {
        source: "/blog/cheapest-way-to-do-social-media-for-business",
        destination: "/blog/best-affordable-social-media-management-small-business",
        permanent: true,
      },
      {
        source: "/cheapest-way-to-do-social-media-for-business",
        destination: "/blog/best-affordable-social-media-management-small-business",
        permanent: true,
      },
      {
        source: "/blog/low-cost-social-media-management",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      {
        source: "/low-cost-social-media-management",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      {
        source: "/blog/cheap-social-media-management",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      {
        source: "/cheap-social-media-management",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      {
        source: "/blog/affordable-social-media-manager",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      {
        source: "/affordable-social-media-manager",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      {
        source: "/affordable-social-media-marketing",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      {
        source: "/blog/affordable-social-media-marketing",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      {
        source: "/low-cost-social-media-marketing",
        destination: "/affordable-social-media-management",
        permanent: true,
      },
      {
        source: "/cheap-social-media-marketing",
        destination: "/affordable-social-media-management",
        permanent: true,
      },

      // === "Posting frequency" consolidation ===
      {
        source: "/blog/posting-frequency-local-business",
        destination: "/blog/how-often-should-local-business-post-social-media-data",
        permanent: true,
      },
      {
        source: "/posting-frequency-local-business",
        destination: "/blog/how-often-should-local-business-post-social-media-data",
        permanent: true,
      },
      {
        source: "/blog/how-often-should-small-businesses-post",
        destination: "/blog/how-often-should-local-business-post-social-media-data",
        permanent: true,
      },
      {
        source: "/how-often-should-small-businesses-post",
        destination: "/blog/how-often-should-local-business-post-social-media-data",
        permanent: true,
      },
      {
        source: "/blog/how-often-should-small-businesses-post-on-social-media",
        destination: "/blog/how-often-should-local-business-post-social-media-data",
        permanent: true,
      },
      {
        source: "/how-often-should-small-businesses-post-on-social-media",
        destination: "/blog/how-often-should-local-business-post-social-media-data",
        permanent: true,
      },

      // === Removed misfit local pages (broken auto-generated content) ===
      {
        source: "/local/social-media-management-roofers",
        destination: "/blog/best-social-media-posting-service-contractors",
        permanent: true,
      },
      {
        source: "/local/social-media-management-lawyers-12-posts-monthly",
        destination: "/blog/best-social-media-service-for-lawyers",
        permanent: true,
      },
      {
        source: "/local/social-media-management-oba-framework",
        destination: "/blog/done-for-you-social-media-guide",
        permanent: true,
      },
      {
        source: "/local/social-media-management-tools-worth",
        destination: "/blog/social-media-tools-local-business",
        permanent: true,
      },

      // === Removed duplicate/thin blog posts → canonical versions ===
      // Buffer comparison cluster → canonical deep comparison
      {
        source: "/blog/glow-social-vs-buffer-comparison",
        destination: "/blog/buffer-vs-glow-social",
        permanent: true,
      },
      {
        source: "/blog/glow-social-vs-buffer-difference-comparison",
        destination: "/blog/buffer-vs-glow-social",
        permanent: true,
      },
      {
        source: "/blog/buffer-vs-ai-content-tools",
        destination: "/blog/buffer-vs-glow-social",
        permanent: true,
      },
      // Hiring SM manager cluster → canonical deep comparison
      {
        source: "/blog/glow-social-vs-hiring-social-media-manager",
        destination: "/blog/social-media-manager-vs-ai",
        permanent: true,
      },
      {
        source: "/blog/glow-social-vs-hiring-social-media-manager-2",
        destination: "/blog/social-media-manager-vs-ai",
        permanent: true,
      },
      {
        source: "/blog/social-media-manager-vs-glow-social",
        destination: "/blog/social-media-manager-vs-ai",
        permanent: true,
      },
      {
        source: "/blog/social-media-manager-vs-automation",
        destination: "/blog/social-media-manager-vs-ai",
        permanent: true,
      },
      // Hootsuite cluster → canonical deep comparison
      {
        source: "/blog/glow-social-vs-hootsuite-done-for-you-vs-diy",
        destination: "/blog/hootsuite-vs-glow-social",
        permanent: true,
      },
      {
        source: "/blog/glow-social-different-hootsuite",
        destination: "/blog/hootsuite-vs-glow-social",
        permanent: true,
      },
      // Generic scheduling tools stub → best tools roundup
      {
        source: "/blog/glow-social-vs-generic-scheduling-tools-local-business",
        destination: "/blog/social-media-tools-local-business",
        permanent: true,
      },
      // Done-for-you duplicates → canonical guide
      {
        source: "/blog/done-for-you-social-media-guide-2",
        destination: "/blog/done-for-you-social-media-guide",
        permanent: true,
      },
      {
        source: "/blog/done-for-you-social-media-lawyers",
        destination: "/blog/done-for-you-ai-social-media-law-firms",
        permanent: true,
      },
      {
        source: "/blog/done-for-you-social-media-attorneys",
        destination: "/blog/done-for-you-ai-social-media-law-firms",
        permanent: true,
      },
      {
        source: "/blog/done-for-you-social-media-roofers-2",
        destination: "/blog/done-for-you-social-media-roofing",
        permanent: true,
      },
      // Agency vs DIY/software comparison stubs → canonical cost comparison
      {
        source: "/blog/social-media-agency-vs-software-vs-diy-costs",
        destination: "/blog/ai-tools-vs-agencies-cost",
        permanent: true,
      },
      {
        source: "/blog/social-media-agency-vs-diy-tool-service-providers",
        destination: "/blog/ai-tools-vs-agencies-cost",
        permanent: true,
      },
      {
        source: "/blog/social-media-agency-vs-automation-cost-results-comparison",
        destination: "/blog/ai-tools-vs-agencies-cost",
        permanent: true,
      },
      // Other thin comparison stubs → best related canonical
      {
        source: "/blog/social-media-tool-vs-platform-local-business",
        destination: "/blog/social-media-tools-local-business",
        permanent: true,
      },
      {
        source: "/blog/oba-framework-vs-viral-trends-local-growth",
        destination: "/blog/oba-social-media-framework-local-business",
        permanent: true,
      },
      {
        source: "/blog/canva-vs-all-in-one-social-media-tools",
        destination: "/blog/social-media-tools-under-50",
        permanent: true,
      },
      // Content strategy duplicate → keep the one with better body
      {
        source: "/blog/why-content-strategy-is-important-for-social-media-success",
        destination: "/blog/why-is-content-strategy-important-for-social-media-success",
        permanent: true,
      },
      // Thin done-for-you stubs → canonical guide
      {
        source: "/blog/is-done-for-you-social-media-worth-it-small-business",
        destination: "/blog/done-for-you-social-media-guide",
        permanent: true,
      },
      {
        source: "/blog/best-done-for-you-social-media-services-small-business",
        destination: "/blog/done-for-you-social-media-guide",
        permanent: true,
      },
      // Thin Glow Social industry stubs → industry pillar posts
      {
        source: "/blog/glow-social-work-gyms",
        destination: "/blog/social-media-fitness-studios",
        permanent: true,
      },
      {
        source: "/blog/glow-social-work-salons",
        destination: "/blog/social-media-salons-spas",
        permanent: true,
      },
      {
        source: "/blog/glow-social-work-restaurants",
        destination: "/blog/social-media-restaurants",
        permanent: true,
      },
      {
        source: "/blog/glow-social-work-retail-stores",
        destination: "/blog/social-media-retail-boutiques",
        permanent: true,
      },
      // Thin Glow Social feature stubs → How It Works page
      {
        source: "/blog/glow-social-ai-content",
        destination: "/how-glow-social-works",
        permanent: true,
      },
      {
        source: "/blog/glow-social-setup-time",
        destination: "/how-glow-social-works",
        permanent: true,
      },

      // === Existing site-structure redirects ===
      {
        source: "/privacy-policy",
        destination: "/privacy",
        permanent: true,
      },
      {
        source: "/terms-conditions",
        destination: "/terms",
        permanent: true,
      },
      {
        source: "/social-media-quiz",
        destination: "/how-glow-social-works",
        permanent: true,
      },
      {
        source: "/locations",
        destination: "/local",
        permanent: true,
      },
      {
        source: "/glow-up",
        destination: "https://app.glowsocial.com/pricing/",
        permanent: true,
      },
      {
        source: "/more",
        destination: "/how-glow-social-works",
        permanent: true,
      },
      {
        source: "/15-min",
        destination: "/lets-meet",
        permanent: true,
      },
      {
        source: "/post-ideas",
        destination: "/blog",
        permanent: true,
      },
      {
        source: "/social-media-tips",
        destination: "/blog",
        permanent: true,
      },
      {
        source: "/social-media-tips/page/:page",
        destination: "/blog",
        permanent: true,
      },
      {
        source: "/go/roofing-playbook/free-month-of-glow-social",
        destination: "/blog/done-for-you-social-media-roofing",
        permanent: true,
      },
      {
        source: "/demo",
        destination: "https://app.glowsocial.com/examples",
        permanent: true,
      },
      {
        source: "/how-ai-social-media-posting-works",
        destination: "/blog/how-ai-social-media-posting-works",
        permanent: true,
      },
      {
        source: "/LinkedIn",
        destination: "/resources/questions/how-to-set-up-linkedin-company-page",
        permanent: true,
      },

      // === Old root-level blog posts → /blog/slug ===
      ...[
        "best-social-media-service-for-lawyers",
        "how-to-get-more-and-more-likes-on-facebook-effective-strategies",
        "glow-social-roofing-social-media-service-2",
        "transform-your-strategy-with-a-social-media-ai-post-generator",
        "guide-to-adding-followers-on-instagram-proven-methods",
        "social-media-stories-boost-engagement-with-ai-powered-content-creation",
        "the-best-time-to-post-tik-toks-on-saturday-for-maximum-engagement",
        "glow-social-contractors-more-calls-social-media",
        "automated-social-media-local-business",
        "automate-social-media-oba-framework",
        "done-for-you-social-media-roofing",
        "50-creative-business-social-media-post-ideas-to-engage-your-audience",
        "social-media-management-images-boost-engagement-with-ai-powered-content",
        "social-media-marketing-ideas-to-elevate-engagement-and-strategy",
        "unlock-social-media-planning-notion-for-streamlined-digital-domination",
        "master-social-media-management-degree-for-career-success-and-digital-growth",
        "unlock-your-career-potential-top-jobs-in-social-media-management-await-you",
        "why-is-content-strategy-important-for-social-media-success",
        "social-media-management-on-instagram-boost-engagement-with-ai-tools",
        "empower-your-strategy-with-inspiring-social-media-management-quotes",
        "social-media-marketing-cost-optimize-your-budget-with-ai-solutions",
        "what-is-media-scheduling-boost-your-social-media-strategy-effortlessly",
        "social-media-management-meaning-elevate-your-strategy-with-ai-tools",
        "understanding-curating-content-meaning-a-comprehensive-overview",
        "social-media-planner-for-small-business-streamline-your-strategy-today",
        "social-media-and-ai-transform-your-digital-dominance-effortlessly",
        "boost-your-engagement-discover-the-benefits-of-social-media-schedulers",
      ].map((slug) => ({
        source: `/${slug}`,
        destination: `/blog/${slug}`,
        permanent: true,
      })),

      // === Old root-level deleted posts that had template content → direct to canonical ===
      { source: "/share-business-opinions-social-media", destination: "/blog/consistent-social-media-without-burnout", permanent: true },
      { source: "/social-media-post-types-local-businesses", destination: "/blog/content-ideas-local-business", permanent: true },

      // === Old root-level deleted posts → direct to canonical (avoid double redirect) ===
      ...[
        { slug: "social-media-agency-vs-software-vs-diy-costs", canonical: "/blog/ai-tools-vs-agencies-cost" },
        { slug: "social-media-manager-vs-glow-social", canonical: "/blog/social-media-manager-vs-ai" },
        { slug: "canva-vs-all-in-one-social-media-tools", canonical: "/blog/social-media-tools-under-50" },
        { slug: "social-media-agency-vs-diy-tool-service-providers", canonical: "/blog/ai-tools-vs-agencies-cost" },
        { slug: "glow-social-different-hootsuite", canonical: "/blog/hootsuite-vs-glow-social" },
        { slug: "glow-social-setup-time", canonical: "/how-glow-social-works" },
        { slug: "how-many-emojis-too-many-social-media", canonical: "/blog/social-media-mistakes-local-business" },
        { slug: "emojis-unprofessional-certain-industries", canonical: "/blog/social-media-mistakes-local-business" },
        { slug: "why-content-strategy-is-important-for-social-media-success", canonical: "/blog/why-is-content-strategy-important-for-social-media-success" },
      ].map(({ slug, canonical }) => ({
        source: `/${slug}`,
        destination: canonical,
        permanent: true,
      })),

      // === Old root-level comparison pages → /compare/slug ===
      ...[
        "agorapulse-alternative",
        "loomly-alternative",
        "chatgpt-alternative",
        "meetedgar-alternative",
      ].map((slug) => ({
        source: `/${slug}`,
        destination: `/compare/${slug}`,
        permanent: true,
      })),

      // === Old local hub pages (generic city-only URLs) → /local ===
      ...[
        "social-media-management-local-business-atlanta",
        "social-media-management-local-business-dallas",
        "social-media-management-local-business-austin",
        "social-media-management-local-business-seattle",
        "social-media-management-local-business-phoenix",
        "social-media-management-local-business-miami",
        "social-media-management-local-business-boston",
      ].map((slug) => ({
        source: `/${slug}`,
        destination: "/local",
        permanent: true,
      })),

      // === GSC coverage drilldown exact-match legacy URLs ===
      // Generated from glowsocial.com-Coverage-Drilldown-2026-06-09.
      // Only exact /blog, /local, /resources/questions, or /compare matches are included.
      ...[
        ["/all-in-one-social-media-app-transform-social-media-management-today", "/blog/best-ai-social-media-content-generators"],
        ["/always-open-digital-presence-client-perception", "/blog/why-customers-check-social-media-before-calling"],
        ["/answer-first-content-clusters-ai-training", "/blog/oba-social-media-framework-local-business"],
        ["/authentic-business-social-media", "/blog/consistent-social-media-without-burnout"],
        ["/auto-detailers-oba-premium-brand", "/blog/best-social-media-service-auto-repair-shops"],
        ["/automate-social-media-oba-framework-2", "/blog/automate-social-media-oba-framework"],
        ["/automated-social-media-for-roofers", "/blog/automated-social-media-roofers-contractors"],
        ["/balance-authenticity-automation-brand-storytelling", "/blog/consistent-social-media-without-burnout"],
        ["/batch-create-social-media-content", "/blog/create-month-content-one-hour"],
        ["/best-platforms-local-business", "/blog/best-platforms-local-business"],
        ["/best-platforms-local-oba-content-strategy", "/blog/oba-social-media-framework-local-business"],
        ["/best-way-automate-social-media-posting", "/blog/how-ai-social-media-posting-works"],
        ["/branded-oba-signals-llm-training", "/blog/oba-social-media-framework-local-business"],
        ["/buffer-vs-glow-social", "/blog/buffer-vs-glow-social"],
        ["/cancel-glow-social-anytime", "/blog/what-makes-glow-social-different"],
        ["/competitors-get-more-clients-oba-solution", "/blog/oba-social-media-framework-local-business"],
        ["/construction-social-media-for-contractors", "/blog/best-social-media-posting-service-contractors"],
        ["/content-ideas-local-business", "/blog/content-ideas-local-business"],
        ["/copy-ai-vs-glow-social", "/blog/copy-ai-vs-glow-social"],
        ["/create-social-media-content-faster", "/blog/how-ai-social-media-posting-works"],
        ["/custom-social-media-posts-for-roofers", "/blog/automated-social-media-roofers-contractors"],
        ["/customers-care-professional-quality-consistency", "/blog/what-makes-customers-trust-business-online"],
        ["/dental-practices-build-trust-oba-frameworks", "/blog/social-media-marketing-dentists"],
        ["/dentist-social-media-service-49month", "/blog/social-media-marketing-dentists"],
        ["/done-for-you-social-media-attorneys", "/blog/done-for-you-ai-social-media-law-firms"],
        ["/done-for-you-social-media-guide", "/blog/done-for-you-social-media-guide"],
        ["/done-for-you-social-media-lawyers", "/blog/done-for-you-ai-social-media-law-firms"],
        ["/done-for-you-social-media-roofers-2", "/blog/done-for-you-social-media-roofing"],
        ["/done-for-you-vs-diy-social-media", "/blog/done-for-you-vs-diy-social-media"],
        ["/effective-oba-offer-posts-local-events", "/blog/oba-social-media-framework-local-business"],
        ["/glow-social-reviews-what-customers-say", "/blog/glow-social-reviews-what-customers-say"],
        ["/glow-social-simplifies-content-creation", "/blog/glow-social-simplifies-content-creation"],
        ["/glow-social-vs-hiring-social-media-manager", "/blog/social-media-manager-vs-ai"],
        ["/glow-social-work-restaurants", "/blog/social-media-restaurants"],
        ["/good-enough-social-media-content", "/blog/consistent-social-media-without-burnout"],
        ["/google-business-profile-vs-social-media", "/blog/google-business-profile-vs-social-media"],
        ["/grow-business-social-media", "/blog/roi-social-media-local-business"],
        ["/grow-without-paying-ads", "/blog/roi-social-media-local-business"],
        ["/healthcare-social-media-management-49-month", "/blog/social-media-healthcare-practices"],
        ["/hootsuite-alternative-no-content-creation", "/blog/hootsuite-alternative-no-content-creation"],
        ["/how-long-try-social-media-before-giving-up", "/blog/real-cost-inconsistent-social-media-posting"],
        ["/how-much-does-social-media-management-cost-in-2025", "/blog/done-for-you-social-media-cost"],
        ["/how-to-get-ai-to-sound-more-human", "/blog/consistent-social-media-without-burnout"],
        ["/human-like-social-media-automation", "/blog/how-ai-social-media-posting-works"],
        ["/is-done-for-you-social-media-worth-it-small-business", "/blog/done-for-you-social-media-guide"],
        ["/law-firms-build-local-authority-oba", "/blog/done-for-you-ai-social-media-law-firms"],
        ["/linkedin-page-local-business", "/blog/best-platforms-local-business"],
        ["/local-businesses-overcome-algorithm-fatigue-community-focus", "/blog/how-often-should-local-business-post-social-media-data"],
        ["/local-consultants-coaches-oba-framework-client-success", "/blog/best-social-media-service-coaches-consultants"],
        ["/local-restaurants-social-media-tips", "/blog/social-media-restaurants"],
        ["/maintain-authenticity-automated-social-media", "/blog/how-ai-social-media-posting-works"],
        ["/maximize-engagement-with-an-app-to-post-to-all-social-media-efficiently", "/blog/best-ai-social-media-content-generators"],
        ["/monitor-social-media-24-7", "/blog/how-social-media-affects-local-business-credibility"],
        ["/need-video-content-social-media", "/blog/content-ideas-local-business"],
        ["/oba-framework-social-media-strategy", "/blog/oba-social-media-framework-local-business"],
        ["/oba-social-media-framework-local-business", "/blog/oba-social-media-framework-local-business"],
        ["/people-tell-content-ai-generated", "/blog/consistent-social-media-without-burnout"],
        ["/personal-story-business-social-media-balance", "/blog/consistent-social-media-without-burnout"],
        ["/physical-therapists-choose-glow-social", "/blog/social-media-healthcare-practices"],
        ["/post-per-day-social-media-frequency", "/blog/how-often-should-local-business-post-social-media-data"],
        ["/pre-written-social-media-content-construction-companies", "/blog/best-social-media-posting-service-contractors"],
        ["/prove-social-media-brings-customers", "/blog/roi-social-media-local-business"],
        ["/quality-over-quantity-social-media-marketing", "/blog/how-often-should-local-business-post-social-media-data"],
        ["/repurpose-blog-post-social-media", "/blog/content-ideas-local-business"],
        ["/roi-of-social-media-local-business", "/blog/roi-social-media-local-business"],
        ["/roi-social-media-local-business", "/blog/roi-social-media-local-business"],
        ["/salons-spas-oba-bookings-staff-client-care", "/blog/social-media-salons-spas"],
        ["/schedule-monitor-social-media-automation", "/blog/how-ai-social-media-posting-works"],
        ["/scheduling-tools-hurt-reach", "/blog/buffer-vs-glow-social"],
        ["/showcase-unique-business-method", "/blog/consistent-social-media-without-burnout"],
        ["/social-media-automation-local-gyms", "/blog/social-media-fitness-studios"],
        ["/social-media-automation-medical-practices", "/blog/social-media-healthcare-practices"],
        ["/social-media-bring-customers-timeline", "/blog/roi-social-media-local-business"],
        ["/social-media-content-relevant-lifespan", "/blog/how-often-should-local-business-post-social-media-data"],
        ["/social-media-for-roofers-49-month", "/blog/automated-social-media-roofers-contractors"],
        ["/social-media-management-accountants-miami", "/local/social-media-management-accountants-miami"],
        ["/social-media-management-accountants-phoenix", "/local/social-media-management-accountants-phoenix"],
        ["/social-media-management-auto-repair-shops-dallas", "/local/social-media-management-auto-repair-shops-dallas"],
        ["/social-media-management-auto-repair-shops-miami", "/local/social-media-management-auto-repair-shops-miami"],
        ["/social-media-management-auto-repair-shops-nashville", "/local/social-media-management-auto-repair-shops-nashville"],
        ["/social-media-management-auto-repair-shops-phoenix", "/local/social-media-management-auto-repair-shops-phoenix"],
        ["/social-media-management-boutique-hotels-austin", "/local/social-media-management-boutique-hotels-austin"],
        ["/social-media-management-boutique-hotels-charlotte", "/local/social-media-management-boutique-hotels-charlotte"],
        ["/social-media-management-boutique-hotels-denver", "/local/social-media-management-boutique-hotels-denver"],
        ["/social-media-management-boutique-hotels-nashville", "/local/social-media-management-boutique-hotels-nashville"],
        ["/social-media-management-dentists-austin", "/local/social-media-management-dentists-austin"],
        ["/social-media-management-dentists-denver", "/local/social-media-management-dentists-denver"],
        ["/social-media-management-dentists-miami", "/local/social-media-management-dentists-miami"],
        ["/social-media-management-dentists-nashville", "/local/social-media-management-dentists-nashville"],
        ["/social-media-management-dentists-seattle", "/local/social-media-management-dentists-seattle"],
        ["/social-media-management-law-firms-charlotte", "/local/social-media-management-law-firms-charlotte"],
        ["/social-media-management-law-firms-denver", "/local/social-media-management-law-firms-denver"],
        ["/social-media-management-law-firms-miami", "/local/social-media-management-law-firms-miami"],
        ["/social-media-management-law-firms-nashville", "/local/social-media-management-law-firms-nashville"],
        ["/social-media-management-law-firms-seattle", "/local/social-media-management-law-firms-seattle"],
        ["/social-media-management-local-gyms-denver", "/local/social-media-management-local-gyms-denver"],
        ["/social-media-management-plumbers-charlotte", "/local/social-media-management-plumbers-charlotte"],
        ["/social-media-management-roofers-atlanta", "/local/social-media-management-roofers-atlanta"],
        ["/social-media-management-roofers-charlotte", "/local/social-media-management-roofers-charlotte"],
        ["/social-media-management-roofers-dallas", "/local/social-media-management-roofers-dallas"],
        ["/social-media-management-roofers-nashville", "/local/social-media-management-roofers-nashville"],
        ["/social-media-management-roofers-seattle", "/local/social-media-management-roofers-seattle"],
        ["/social-media-management-wedding-photographers-atlanta", "/local/social-media-management-wedding-photographers-atlanta"],
        ["/social-media-management-wedding-photographers-denver", "/local/social-media-management-wedding-photographers-denver"],
        ["/social-media-manager-vs-ai", "/blog/social-media-manager-vs-ai"],
        ["/social-media-mistakes-local-business", "/blog/social-media-mistakes-local-business"],
        ["/social-media-replace-phone-support", "/blog/how-social-media-affects-local-business-credibility"],
        ["/social-media-salons-spas", "/blog/social-media-salons-spas"],
        ["/social-media-tips-plumbers-electricians", "/blog/best-social-media-posting-service-home-services"],
        ["/social-media-tool-vs-platform-local-business", "/blog/social-media-tools-local-business"],
        ["/social-media-workflow-wedding-photographers", "/blog/best-social-media-service-wedding-vendors"],
        ["/stop-losing-jobs-better-instagram-glow-social", "/blog/automated-social-media-roofers-contractors"],
        ["/technical-experts-social-media-oba", "/blog/best-social-media-service-busy-business-owners"],
        ["/tiktok-local-business-marketing-strategy", "/blog/best-platforms-local-business"],
        ["/transform-your-social-media-marketing-chicago-with-ai-powered-solutions", "/blog/automated-social-media-local-business"],
        ["/unlock-efficiency-with-a-social-media-marketing-app-for-your-brand", "/blog/best-ai-social-media-content-generators"],
        ["/use-stock-photos-business-social-media", "/blog/social-media-management-images-boost-engagement-with-ai-powered-content"],
        ["/what-makes-glow-social-different", "/blog/what-makes-glow-social-different"],
        ["/what-to-look-for-in-a-social-media-posting-service", "/blog/what-makes-glow-social-different"],
        ["/why-glow-social-isnt-another-social-media-app-and-why-thats-exactly-the-point", "/blog/what-makes-glow-social-different"],
        ["/why-service-businesses-choose-glow-social", "/blog/what-makes-glow-social-different"],
      ].map(([source, destination]) => ({
        source,
        destination,
        permanent: true,
      })),

      // === GSC 404 cleanup exact-match/root-variant redirects ===
      // Generated from glowsocial.com-Coverage-Drilldown-2026-06-09.
      // Includes exact live content matches and root variants of existing canonical redirects.
      ...[
        ["/top-5-automated-social-media-tools-small-business-2026", "/blog/top-5-automated-social-media-tools-small-business-2026"],
        ["/touchpoints-social-media-follower-buys", "/blog/roi-social-media-local-business"],
        ["/what-does-glow-social-include-complete-breakdown", "/blog/what-makes-glow-social-different"],
        ["/best-social-media-management-app-enhance-your-online-strategy-today", "/blog/best-ai-social-media-content-generators"],
        ["/social-media-management-auto-repair-shops-austin", "/local/social-media-management-auto-repair-shops-austin"],
        ["/the-glow-method-social-media-automation", "/blog/the-glow-method-social-media-automation"],
        ["/social-media-management-plumbers-atlanta", "/local/social-media-management-plumbers-atlanta"],
        ["/social-media-management-auto-repair-shops-charlotte", "/local/social-media-management-auto-repair-shops-charlotte"],
        ["/best-time-post-social-media-local-business", "/blog/how-often-should-local-business-post-social-media-data"],
        ["/social-media-management-auto-repair-shops-seattle", "/local/social-media-management-auto-repair-shops-seattle"],
        ["/social-media-management-roofers-miami", "/local/social-media-management-roofers-miami"],
        ["/social-media-management-med-spas-chicago", "/local/social-media-management-med-spas-chicago"],
        ["/home", "/"],
        ["/social-media-management-dentists-charlotte", "/local/social-media-management-dentists-charlotte"],
        ["/metricool-alternative", "/compare/metricool-alternative"],
        ["/automated-social-media-roofers-contractors", "/blog/automated-social-media-roofers-contractors"],
        ["/social-media-content-generator-auto-repair-shops", "/blog/best-social-media-service-auto-repair-shops"],
        ["/crowdfire-alternative", "/compare/crowdfire-alternative"],
        ["/best-social-media-posting-service-dentists", "/blog/best-social-media-posting-service-dentists"],
        ["/social-media-management-tools-worth", "/blog/social-media-tools-local-business"],
        ["/best-ai-tool-for-social-media", "/blog/best-ai-social-media-content-generators"],
        ["/hootsuite-vs-glow-social", "/blog/hootsuite-vs-glow-social"],
        ["/social-media-management-accountants-seattle", "/local/social-media-management-accountants-seattle"],
        ["/social-media-management-accountants-austin", "/local/social-media-management-accountants-austin"],
        ["/social-media-management-accountants-charlotte", "/local/social-media-management-accountants-charlotte"],
        ["/glow-social-work-gyms", "/blog/social-media-fitness-studios"],
        ["/social-media-management-med-spas-phoenix", "/local/social-media-management-med-spas-phoenix"],
        ["/social-media-tools-cost-per-month", "/blog/done-for-you-social-media-cost"],
        ["/social-media-strategy-med-spas-estheticians", "/blog/social-media-salons-spas"],
        ["/sprout-social-vs-glow-social", "/blog/sprout-social-vs-glow-social"],
        ["/glow-social-work-retail-stores", "/blog/social-media-retail-boutiques"],
        ["/automation-save-time-small-business", "/blog/how-ai-social-media-posting-works"],
        ["/diy-social-media-cost-calculator", "/blog/done-for-you-social-media-cost"],
        ["/best-social-media-service-coaches-consultants", "/blog/best-social-media-service-coaches-consultants"],
        ["/how-to-generate-social-media-content-with-ai", "/blog/how-ai-social-media-posting-works"],
        ["/buffer-vs-ai-content-tools", "/blog/buffer-vs-glow-social"],
        ["/social-media-management-law-firms-chicago", "/local/social-media-management-law-firms-chicago"],
        ["/empty-social-media-profiles-hurt-business", "/blog/real-cost-inconsistent-social-media-posting"],
        ["/best-social-media-service-landscapers", "/blog/best-social-media-service-landscapers"],
        ["/what-happens-if-you-dont-post-on-social-media-regularly", "/blog/real-cost-inconsistent-social-media-posting"],
        ["/social-media-management-plumbers-phoenix", "/local/social-media-management-plumbers-phoenix"],
        ["/social-media-management-plumbers-chicago", "/local/social-media-management-plumbers-chicago"],
        ["/social-media-management-local-gyms-charlotte", "/local/social-media-management-local-gyms-charlotte"],
        ["/social-media-management-law-firms-dallas", "/local/social-media-management-law-firms-dallas"],
        ["/social-media-management-dentists-atlanta", "/local/social-media-management-dentists-atlanta"],
        ["/social-media-content-strategy-local-retail", "/blog/social-media-retail-boutiques"],
        ["/social-media-management-plumbers-seattle", "/local/social-media-management-plumbers-seattle"],
        ["/social-media-management-med-spas-dallas", "/local/social-media-management-med-spas-dallas"],
        ["/social-media-tools-local-business", "/blog/social-media-tools-local-business"],
        ["/7-ways-local-businesses-cut-marketing-costs-2026", "/blog/7-ways-local-businesses-cut-marketing-costs-2026"],
        ["/best-social-media-tools-that-post-for-you", "/blog/best-ai-social-media-content-generators"],
        ["/schedule-social-media-posts-advance", "/blog/how-ai-social-media-posting-works"],
        ["/oba-framework-first-week-content-plan", "/blog/oba-social-media-framework-local-business"],
        ["/glow-social-ai-content", "/how-glow-social-works"],
        ["/screenshot-customer-reviews-post", "/blog/social-media-management-images-boost-engagement-with-ai-powered-content"],
        ["/best-social-media-service-photographers", "/blog/best-social-media-service-photographers"],
        ["/buffer-hootsuite-glow-social-oba-framework-comparison", "/blog/buffer-vs-glow-social"],
        ["/best-set-and-forget-social-media-small-business", "/blog/best-ai-social-media-content-generators"],
        ["/lawyers-build-authority-ethically", "/blog/done-for-you-ai-social-media-law-firms"],
        ["/social-media-management-accountants-chicago", "/local/social-media-management-accountants-chicago"],
        ["/best-social-media-posting-service-salons", "/blog/best-social-media-posting-service-salons"],
        ["/social-media-management-local-gyms-austin", "/local/social-media-management-local-gyms-austin"],
        ["/best-social-media-service-real-estate-agents", "/blog/best-social-media-service-real-estate-agents"],
        ["/glow-social-difference-ai-content-platforms", "/blog/glow-social-difference-ai-content-platforms"],
        ["/social-media-management-law-firms-phoenix", "/local/social-media-management-law-firms-phoenix"],
        ["/bad-social-media-advice-local-business", "/blog/bad-social-media-advice-local-business"],
        ["/done-for-you-social-media-guide-2", "/blog/done-for-you-social-media-guide"],
        ["/social-media-management-dentists-chicago", "/local/social-media-management-dentists-chicago"],
        ["/best-social-media-service-busy-business-owners", "/blog/best-social-media-service-busy-business-owners"],
        ["/glow-social-get-more-customers", "/blog/glow-social-get-more-customers"],
        ["/glow-social-vs-generic-scheduling-tools-local-business", "/blog/social-media-tools-local-business"],
        ["/best-social-media-automation-tools-small-business", "/blog/best-ai-social-media-content-generators"],
        ["/automated-manual-social-media-posting-better", "/blog/how-ai-social-media-posting-works"],
        ["/social-media-accountants-bookkeepers", "/blog/social-media-accountants-bookkeepers"],
        ["/social-media-cost-comparison-manual-scheduling-voice-matched", "/blog/social-media-cost-comparison-manual-scheduling-voice-matched"],
        ["/hashtags-work-2025-strategies", "/blog/social-media-mistakes-local-business"],
        ["/follower-count-engagement-matter", "/blog/roi-social-media-local-business"],
        ["/glow-social-smart-feed-industry-updates", "/blog/glow-social-smart-feed-industry-updates"],
        ["/canva-templates-good-business", "/blog/social-media-management-images-boost-engagement-with-ai-powered-content"],
        ["/consistent-social-media-without-burnout", "/blog/consistent-social-media-without-burnout"],
        ["/best-social-media-manager-alternatives-small-business", "/blog/best-social-media-manager-alternatives-small-business"],
        ["/professional-photos-social-media-necessary", "/blog/social-media-management-images-boost-engagement-with-ai-powered-content"],
        ["/glow-social-work-salons", "/blog/social-media-salons-spas"],
        ["/local-business-post-go-viral", "/blog/content-ideas-local-business"],
        ["/social-media-management-oba-framework", "/blog/done-for-you-social-media-guide"],
        ["/best-posting-schedule-service-businesses", "/blog/how-often-should-local-business-post-social-media-data"],
        ["/best-social-media-service-local-businesses-under-100-month", "/blog/best-social-media-service-local-businesses-under-100-month"],
        ["/best-done-for-you-social-media-services-small-business", "/blog/done-for-you-social-media-guide"],
        ["/social-media-changing-businesses-automation-ai", "/blog/how-ai-social-media-posting-works"],
        ["/engagement-replace-traditional-networking", "/blog/roi-social-media-local-business"],
        ["/create-month-content-one-hour", "/blog/create-month-content-one-hour"],
        ["/oba-framework-content-strategy-glow-social", "/blog/oba-social-media-framework-local-business"],
        ["/best-social-media-posting-service-contractors", "/blog/best-social-media-posting-service-contractors"],
        ["/best-social-media-service-insurance-agents", "/blog/best-social-media-service-insurance-agents"],
        ["/best-social-media-service-cleaning-companies", "/blog/best-social-media-service-cleaning-companies"],
        ["/best-social-media-platforms-service-businesses", "/blog/best-platforms-local-business"],
        ["/overcome-writers-block-social-media-oba-framework", "/blog/oba-social-media-framework-local-business"],
        ["/respond-customer-questions-social-media", "/blog/how-social-media-affects-local-business-credibility"],
        ["/best-social-media-service-one-person-businesses", "/blog/best-social-media-service-one-person-businesses"],
        ["/social-media-fitness-studios", "/blog/social-media-fitness-studios"],
        ["/best-social-media-service-auto-repair-shops", "/blog/best-social-media-service-auto-repair-shops"],
        ["/social-media-management-accountants-dallas", "/local/social-media-management-accountants-dallas"],
        ["/tailwind-alternative", "/compare/tailwind-alternative"],
        ["/social-media-boutique-fitness", "/blog/social-media-fitness-studios"],
        ["/social-media-retail-boutiques", "/blog/social-media-retail-boutiques"],
        ["/zoho-social-alternative", "/compare/zoho-social-alternative"],
        ["/the-best-app-for-scheduling-social-media-posts-boost-your-strategy-effortlessly", "/blog/best-ai-social-media-content-generators"],
        ["/social-media-management-plumbers-austin", "/local/social-media-management-plumbers-austin"],
        ["/later-alternative", "/compare/later-alternative"],
        ["/same-caption-instagram-facebook", "/blog/best-platforms-local-business"],
        ["/best-social-media-posting-service-restaurants", "/blog/best-social-media-posting-service-restaurants"],
        ["/social-media-management-boutique-hotels-dallas", "/local/social-media-management-boutique-hotels-dallas"],
        ["/social-media-management-boutique-hotels-miami", "/local/social-media-management-boutique-hotels-miami"],
        ["/social-media-management-plumbers-miami", "/local/social-media-management-plumbers-miami"],
        ["/compete-bigger-businesses-social-media", "/blog/roi-social-media-local-business"],
        ["/social-media-management-local-gyms-phoenix", "/local/social-media-management-local-gyms-phoenix"],
        ["/oba-framework-vs-viral-trends-local-growth", "/blog/oba-social-media-framework-local-business"],
        ["/social-media-management-wedding-photographers-seattle", "/local/social-media-management-wedding-photographers-seattle"],
        ["/master-social-media-scheduling-boost-engagement-with-ai-automation", "/blog/best-ai-social-media-content-generators"],
        ["/done-for-you-ai-social-media-law-firms", "/blog/done-for-you-ai-social-media-law-firms"],
        ["/social-media-management-auto-repair-shops-denver", "/local/social-media-management-auto-repair-shops-denver"],
        ["/glow-social-posts-per-month", "/blog/glow-social-posts-per-month"],
        ["/best-social-media-service-medical-practices", "/blog/best-social-media-service-medical-practices"],
        ["/glow-social-vs-buffer-comparison", "/blog/buffer-vs-glow-social"],
        ["/done-for-you-social-media-cost", "/blog/done-for-you-social-media-cost"],
        ["/social-media-management-wedding-photographers-dallas", "/local/social-media-management-wedding-photographers-dallas"],
        ["/social-media-automation-financial-advisors-accountants", "/blog/best-social-media-service-for-accountants"],
        ["/professional-services-social-media-management", "/blog/best-social-media-service-busy-business-owners"],
        ["/real-estate-social-media-management", "/blog/best-social-media-service-real-estate-agents"],
        ["/glow-social-fixes-last-posted-problem", "/blog/glow-social-fixes-last-posted-problem"],
        ["/social-media-marketing-examples-elevate-your-strategy-with-ai-solutions", "/blog/social-media-marketing-ideas-to-elevate-engagement-and-strategy"],
        ["/best-social-media-service-wedding-vendors", "/blog/best-social-media-service-wedding-vendors"],
        ["/best-small-business-social-media-practices-2025", "/blog/best-platforms-local-business"],
        ["/jasper-vs-glow-social", "/blog/jasper-vs-glow-social"],
        ["/social-media-management-wedding-photographers-miami", "/local/social-media-management-wedding-photographers-miami"],
        ["/social-media-real-estate-agents", "/blog/social-media-real-estate-agents"],
        ["/best-social-media-service-for-accountants", "/blog/best-social-media-service-for-accountants"],
        ["/social-media-healthcare-practices", "/blog/social-media-healthcare-practices"],
        ["/plann-alternative", "/compare/plann-alternative"],
        ["/top-social-media-apps-enhance-strategy-with-ai-powered-solutions", "/blog/best-ai-social-media-content-generators"],
        ["/social-media-management-law-firms-austin", "/local/social-media-management-law-firms-austin"],
        ["/social-media-management-local-gyms-atlanta", "/local/social-media-management-local-gyms-atlanta"],
        ["/social-media-management-local-gyms-miami", "/local/social-media-management-local-gyms-miami"],
        ["/planoly-alternative", "/compare/planoly-alternative"],
        ["/coschedule-alternative", "/compare/coschedule-alternative"],
      ].map(([source, destination]) => ({
        source,
        destination,
        permanent: true,
      })),

      // === Old WordPress category/author pagination → /blog ===
      {
        source: "/category/:path*",
        destination: "/blog",
        permanent: true,
      },
      {
        source: "/author/:path*",
        destination: "/blog",
        permanent: true,
      },

      // === Template-duplicate blog posts → canonical versions ===
      ...[
        { slug: "49-social-media-management-roofers", canonical: "/blog/automated-social-media-roofers-contractors" },
        { slug: "ai-replace-social-media-manager", canonical: "/blog/social-media-manager-vs-ai" },
        { slug: "ai-replacing-google-local-business-discovery", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "all-in-one-social-media-app-transform-social-media-management-today", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "always-open-digital-presence-client-perception", canonical: "/blog/why-customers-check-social-media-before-calling" },
        { slug: "answer-first-content-clusters-ai-training", canonical: "/blog/oba-social-media-framework-local-business" },
        { slug: "auto-detailers-oba-premium-brand", canonical: "/blog/best-social-media-service-auto-repair-shops" },
        { slug: "automate-social-media-oba-framework-2", canonical: "/blog/automate-social-media-oba-framework" },
        { slug: "automated-manual-social-media-posting-better", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "automated-social-media-for-roofers", canonical: "/blog/automated-social-media-roofers-contractors" },
        { slug: "authentic-business-social-media", canonical: "/blog/consistent-social-media-without-burnout" },
        { slug: "automation-save-time-small-business", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "average-time-spent-social-media-marketing", canonical: "/blog/average-time-social-media-marketing" },
        { slug: "balance-authenticity-automation-brand-storytelling", canonical: "/blog/consistent-social-media-without-burnout" },
        { slug: "batch-create-social-media-content", canonical: "/blog/create-month-content-one-hour" },
        { slug: "best-ai-tool-for-social-media", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "best-app-for-scheduling-posts-elevate-social-media-management-effortlessly", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "best-app-for-social-media-posts-boost-engagement-effortlessly", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "best-app-to-schedule-social-media-posts-for-effortless-management", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "best-apps-for-social-media-marketing-enhance-engagement-effortlessly", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "best-platforms-local-oba-content-strategy", canonical: "/blog/oba-social-media-framework-local-business" },
        { slug: "best-posting-schedule-service-businesses", canonical: "/blog/how-often-should-local-business-post-social-media-data" },
        { slug: "best-set-and-forget-social-media-small-business", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "best-small-business-social-media-practices-2025", canonical: "/blog/best-platforms-local-business" },
        { slug: "best-social-media-automation-tools-small-business", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "best-social-media-management-app-enhance-your-online-strategy-today", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "best-social-media-platforms-service-businesses", canonical: "/blog/best-platforms-local-business" },
        { slug: "best-social-media-posting-apps-to-streamline-your-marketing-efforts", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "best-social-media-tools-that-post-for-you", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "best-time-post-social-media-local-business", canonical: "/blog/how-often-should-local-business-post-social-media-data" },
        { slug: "best-way-automate-social-media-posting", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "best-way-stay-visible-customers-online", canonical: "/blog/why-customers-check-social-media-before-calling" },
        { slug: "biggest-challenge-social-media-marketing", canonical: "/blog/social-media-mistakes-local-business" },
        { slug: "boost-your-social-media-management-with-an-app-to-schedule-posts", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "branded-oba-signals-llm-training", canonical: "/blog/oba-social-media-framework-local-business" },
        { slug: "buffer-hootsuite-glow-social-oba-framework-comparison", canonical: "/blog/buffer-vs-glow-social" },
        { slug: "cancel-glow-social-anytime", canonical: "/blog/what-makes-glow-social-different" },
        { slug: "canva-templates-good-business", canonical: "/blog/social-media-management-images-boost-engagement-with-ai-powered-content" },
        { slug: "compete-bigger-businesses-social-media", canonical: "/blog/roi-social-media-local-business" },
        { slug: "competitors-get-more-clients-oba-solution", canonical: "/blog/oba-social-media-framework-local-business" },
        { slug: "construction-social-media-for-contractors", canonical: "/blog/best-social-media-posting-service-contractors" },
        { slug: "create-social-media-content-faster", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "custom-social-media-posts-for-roofers", canonical: "/blog/automated-social-media-roofers-contractors" },
        { slug: "customers-care-professional-quality-consistency", canonical: "/blog/what-makes-customers-trust-business-online" },
        { slug: "dental-practices-build-trust-oba-frameworks", canonical: "/blog/social-media-marketing-dentists" },
        { slug: "dentist-social-media-service-49month", canonical: "/blog/social-media-marketing-dentists" },
        { slug: "diy-social-media-cost-calculator", canonical: "/blog/done-for-you-social-media-cost" },
        { slug: "effective-oba-offer-posts-local-events", canonical: "/blog/oba-social-media-framework-local-business" },
        { slug: "emojis-unprofessional-certain-industries", canonical: "/blog/social-media-mistakes-local-business" },
        { slug: "empty-social-media-profiles-hurt-business", canonical: "/blog/real-cost-inconsistent-social-media-posting" },
        { slug: "engagement-replace-traditional-networking", canonical: "/blog/roi-social-media-local-business" },
        { slug: "follower-count-engagement-matter", canonical: "/blog/roi-social-media-local-business" },
        { slug: "good-enough-social-media-content", canonical: "/blog/consistent-social-media-without-burnout" },
        { slug: "grow-business-social-media", canonical: "/blog/roi-social-media-local-business" },
        { slug: "grow-without-paying-ads", canonical: "/blog/roi-social-media-local-business" },
        { slug: "hashtags-work-2025-strategies", canonical: "/blog/social-media-mistakes-local-business" },
        { slug: "healthcare-social-media-management-49-month", canonical: "/blog/social-media-healthcare-practices" },
        { slug: "hire-social-media-manager-or-do-it-yourself", canonical: "/blog/freelance-social-media-manager-charge-cost" },
        { slug: "hours-per-week-social-media-takes", canonical: "/blog/average-time-social-media-marketing" },
        { slug: "how-long-manage-social-media", canonical: "/blog/average-time-social-media-marketing" },
        { slug: "how-long-try-social-media-before-giving-up", canonical: "/blog/real-cost-inconsistent-social-media-posting" },
        { slug: "how-many-emojis-too-many-social-media", canonical: "/blog/social-media-mistakes-local-business" },
        { slug: "how-much-does-social-media-management-cost-in-2025", canonical: "/blog/done-for-you-social-media-cost" },
        { slug: "how-often-should-small-businesses-post-on-social-media", canonical: "/blog/how-often-should-local-business-post-social-media-data" },
        { slug: "how-to-generate-social-media-content-with-ai", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "how-to-get-ai-to-sound-more-human", canonical: "/blog/consistent-social-media-without-burnout" },
        { slug: "how-to-get-more-customers-from-social-media", canonical: "/blog/roi-social-media-local-business" },
        { slug: "how-to-schedule-social-media-posts-automatically", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "human-like-social-media-automation", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "law-firms-build-local-authority-oba", canonical: "/blog/done-for-you-ai-social-media-law-firms" },
        { slug: "lawyers-build-authority-ethically", canonical: "/blog/done-for-you-ai-social-media-law-firms" },
        { slug: "linkedin-page-local-business", canonical: "/blog/best-platforms-local-business" },
        { slug: "local-business-post-go-viral", canonical: "/blog/content-ideas-local-business" },
        { slug: "local-businesses-overcome-algorithm-fatigue-community-focus", canonical: "/blog/how-often-should-local-business-post-social-media-data" },
        { slug: "local-consultants-coaches-oba-framework-client-success", canonical: "/blog/best-social-media-service-coaches-consultants" },
        { slug: "local-restaurants-social-media-tips", canonical: "/blog/social-media-restaurants" },
        { slug: "maintain-authenticity-automated-social-media", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "master-social-media-scheduling-boost-engagement-with-ai-automation", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "maximize-engagement-with-an-app-to-post-to-all-social-media-efficiently", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "monitor-social-media-24-7", canonical: "/blog/how-social-media-affects-local-business-credibility" },
        { slug: "need-video-content-social-media", canonical: "/blog/content-ideas-local-business" },
        { slug: "oba-framework-content-strategy-glow-social", canonical: "/blog/oba-social-media-framework-local-business" },
        { slug: "oba-framework-first-week-content-plan", canonical: "/blog/oba-social-media-framework-local-business" },
        { slug: "oba-framework-social-media-strategy", canonical: "/blog/oba-social-media-framework-local-business" },
        { slug: "overcome-writers-block-social-media-oba-framework", canonical: "/blog/oba-social-media-framework-local-business" },
        { slug: "people-tell-content-ai-generated", canonical: "/blog/consistent-social-media-without-burnout" },
        { slug: "personal-story-business-social-media-balance", canonical: "/blog/consistent-social-media-without-burnout" },
        { slug: "physical-therapists-choose-glow-social", canonical: "/blog/social-media-healthcare-practices" },
        { slug: "post-per-day-social-media-frequency", canonical: "/blog/how-often-should-local-business-post-social-media-data" },
        { slug: "pre-written-social-media-content-construction-companies", canonical: "/blog/best-social-media-posting-service-contractors" },
        { slug: "professional-photos-social-media-necessary", canonical: "/blog/social-media-management-images-boost-engagement-with-ai-powered-content" },
        { slug: "professional-services-social-media-management", canonical: "/blog/best-social-media-service-busy-business-owners" },
        { slug: "prove-social-media-brings-customers", canonical: "/blog/roi-social-media-local-business" },
        { slug: "quality-over-quantity-social-media-marketing", canonical: "/blog/how-often-should-local-business-post-social-media-data" },
        { slug: "real-estate-social-media-management", canonical: "/blog/best-social-media-service-real-estate-agents" },
        { slug: "repurpose-blog-post-social-media", canonical: "/blog/content-ideas-local-business" },
        { slug: "respond-customer-questions-social-media", canonical: "/blog/how-social-media-affects-local-business-credibility" },
        { slug: "roi-of-social-media-local-business", canonical: "/blog/roi-social-media-local-business" },
        { slug: "salons-spas-oba-bookings-staff-client-care", canonical: "/blog/social-media-salons-spas" },
        { slug: "same-caption-instagram-facebook", canonical: "/blog/best-platforms-local-business" },
        { slug: "schedule-monitor-social-media-automation", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "schedule-social-media-posts-advance", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "scheduling-tools-hurt-reach", canonical: "/blog/buffer-vs-glow-social" },
        { slug: "screenshot-customer-reviews-post", canonical: "/blog/social-media-management-images-boost-engagement-with-ai-powered-content" },
        { slug: "share-business-opinions-social-media", canonical: "/blog/consistent-social-media-without-burnout" },
        { slug: "showcase-unique-business-method", canonical: "/blog/consistent-social-media-without-burnout" },
        { slug: "social-media-automation-financial-advisors-accountants", canonical: "/blog/best-social-media-service-for-accountants" },
        { slug: "social-media-automation-local-gyms", canonical: "/blog/social-media-fitness-studios" },
        { slug: "social-media-automation-medical-practices", canonical: "/blog/social-media-healthcare-practices" },
        { slug: "social-media-boutique-fitness", canonical: "/blog/social-media-fitness-studios" },
        { slug: "social-media-bring-customers-timeline", canonical: "/blog/roi-social-media-local-business" },
        { slug: "social-media-changing-businesses-automation-ai", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "social-media-consistency-tools-oba-framework", canonical: "/blog/oba-social-media-framework-local-business" },
        { slug: "social-media-content-generator-auto-repair-shops", canonical: "/blog/best-social-media-service-auto-repair-shops" },
        { slug: "social-media-content-relevant-lifespan", canonical: "/blog/how-often-should-local-business-post-social-media-data" },
        { slug: "social-media-content-strategy-local-retail", canonical: "/blog/social-media-retail-boutiques" },
        { slug: "social-media-for-roofers-49-month", canonical: "/blog/automated-social-media-roofers-contractors" },
        { slug: "social-media-manager-cost-hiring-budget", canonical: "/blog/freelance-social-media-manager-charge-cost" },
        { slug: "social-media-marketing-examples-elevate-your-strategy-with-ai-solutions", canonical: "/blog/social-media-marketing-ideas-to-elevate-engagement-and-strategy" },
        { slug: "social-media-post-types-local-businesses", canonical: "/blog/content-ideas-local-business" },
        { slug: "social-media-replace-phone-support", canonical: "/blog/how-social-media-affects-local-business-credibility" },
        { slug: "social-media-strategy-med-spas-estheticians", canonical: "/blog/social-media-salons-spas" },
        { slug: "social-media-tips-plumbers-electricians", canonical: "/blog/best-social-media-posting-service-home-services" },
        { slug: "social-media-tools-boutique-hotels", canonical: "/blog/best-social-media-service-busy-business-owners" },
        { slug: "social-media-tools-cost-per-month", canonical: "/blog/done-for-you-social-media-cost" },
        { slug: "social-media-workflow-wedding-photographers", canonical: "/blog/best-social-media-service-wedding-vendors" },
        { slug: "stop-losing-jobs-better-instagram-glow-social", canonical: "/blog/automated-social-media-roofers-contractors" },
        { slug: "technical-experts-social-media-oba", canonical: "/blog/best-social-media-service-busy-business-owners" },
        { slug: "the-best-app-for-scheduling-social-media-posts-boost-your-strategy-effortlessly", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "the-real-cost-of-social-media-management-comparing-your-options-in-2025", canonical: "/blog/freelance-social-media-manager-charge-cost" },
        { slug: "tiktok-local-business-marketing-strategy", canonical: "/blog/best-platforms-local-business" },
        { slug: "top-social-media-apps-enhance-strategy-with-ai-powered-solutions", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "top-social-media-marketing-agencies-for-effective-digital-domination", canonical: "/blog/ai-tools-vs-agencies-cost" },
        { slug: "touchpoints-social-media-follower-buys", canonical: "/blog/roi-social-media-local-business" },
        { slug: "transform-your-social-media-marketing-chicago-with-ai-powered-solutions", canonical: "/blog/automated-social-media-local-business" },
        { slug: "unlock-efficiency-with-a-social-media-marketing-app-for-your-brand", canonical: "/blog/best-ai-social-media-content-generators" },
        { slug: "use-stock-photos-business-social-media", canonical: "/blog/social-media-management-images-boost-engagement-with-ai-powered-content" },
        { slug: "what-does-glow-social-include-complete-breakdown", canonical: "/blog/what-makes-glow-social-different" },
        { slug: "what-happens-if-you-dont-post-on-social-media-regularly", canonical: "/blog/real-cost-inconsistent-social-media-posting" },
        { slug: "what-to-look-for-in-a-social-media-posting-service", canonical: "/blog/what-makes-glow-social-different" },
        { slug: "why-businesses-post-more-automated-social-media", canonical: "/blog/how-ai-social-media-posting-works" },
        { slug: "why-glow-social-isnt-another-social-media-app-and-why-thats-exactly-the-point", canonical: "/blog/what-makes-glow-social-different" },
        { slug: "why-service-businesses-choose-glow-social", canonical: "/blog/what-makes-glow-social-different" },
        { slug: "why-social-media-managers-expensive", canonical: "/blog/freelance-social-media-manager-charge-cost" },
      ].map(({ slug, canonical }) => ({
        source: `/blog/${slug}`,
        destination: canonical,
        permanent: true,
      })),
    ];
  },
};

export default nextConfig;
